name: Build PyTorch Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # You can specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision 
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          cd docs
          make html
      - name: Upload documentation artifact
      - uses: actions/upload-artifact@v3
        with:
          name: Built-Docs
          path: docs/build/html/

  upload:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository == 'svekars/sphinx-read-thedocs-test' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          persist-credentials: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Doc-Build
          path: docs
      - name: Add no-index tag
        run: |
          REF_NAME=$(echo "${{ github.ref }}")
          echo "Ref name: ${REF_NAME}"
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            find docs -name "*.html" -print0 | xargs -0 sed -i '/<head>/a \ \ <meta name="robots" content="noindex">';
          fi
      - name: Move and commit changes
        run: |
          set -euo pipefail
          # Get github.ref for the output doc folder. By default "main"
          # If matches a tag like refs/tags/v1.12.0-rc3 or
          # refs/tags/v1.12.0 convert to 1.12
          GITHUB_REF=${{ github.ref }}

          # Convert refs/tags/v1.12.0rc3 into 1.12.
          # Adopted from https://github.com/pytorch/pytorch/blob/main/.github/workflows/_docs.yml#L150C11-L155C13
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+\.[0-9]+)\.* ]]; then
            TARGET_FOLDER="${BASH_REMATCH[1]}"
          else
            TARGET_FOLDER="main"
          fi
          echo "Target Folder: ${TARGET_FOLDER}"

          mkdir -p "${TARGET_FOLDER}"
          rm -rf "${TARGET_FOLDER}"/*
          mv docs/* "${TARGET_FOLDER}"

          git config user.name 'svekars'
          git config user.email 'svekars@meta.com'
          git add "${TARGET_FOLDER}" || true
          git commit -m "auto-generating sphinx docs" || true
          git push -f
